version: 0.0
os: linux
files:
  - source: /
    destination: /var/server/
permissions:
  - object: /home/ec2-user/
    owner: root
    group: root
    mode: 777
  - object: /var/server
    owner: root
    group: root
    mode: 777
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      runas: root
      timeout: 300
