#!/bin/bash
cd /var/server/

export PATH="/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"

docker-compose -f docker-compose.yml down
docker-compose -f docker-compose.yml up --build -d